use anyhow::Result;
use colored::Colorize;
use std::path::Path;

use crate::system::{self, domain_to_user, fpm_pool_path, fpm_socket_path, reload_fpm, run};

fn pool_config(domain: &str, php: &str) -> String {
    let user = domain_to_user(domain);
    let socket = fpm_socket_path(domain, php);
    format!(
        "; PHP-FPM pool for {domain}
; Generated by sitectl

[{domain}]
user = {user}
group = {user}
listen = {socket}
listen.owner = www-data
listen.group = www-data

pm = dynamic
pm.max_children = 10
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3
pm.max_requests = 500

; Restrict PHP to .php files only
security.limit_extensions = .php
"
    )
}

pub fn cmd_add(domain: &str, php: &str) -> Result<()> {
    let pool_path = fpm_pool_path(domain, php);

    if pool_path.exists() {
        println!("{} pool already exists at {}", "warn:".yellow(), pool_path.display());
        return Ok(());
    }

    let user = domain_to_user(domain);
    if !system::user_exists(&user) {
        run(
            "useradd",
            &[
                "--system",
                "--no-create-home",
                "--shell", "/usr/sbin/nologin",
                "--home-dir", &format!("/var/www/{domain}"),
                &user,
            ],
        )?;
        println!("{} system user '{user}'", "created:".green());
    }

    std::fs::write(&pool_path, pool_config(domain, php))?;
    println!("{} {}", "created:".green(), pool_path.display());

    reload_fpm(php)?;
    println!("{} php{php}-fpm", "reloaded:".green());

    Ok(())
}

pub fn cmd_list() -> Result<()> {
    let versions = system::available_php_versions();

    println!(
        "{:<35} {:<8} {:<20} {:<10}",
        "Pool (domain)".bold(),
        "PHP".bold(),
        "User".bold(),
        "Socket".bold()
    );
    println!("{}", "-".repeat(80));

    let mut found = false;
    for php in &versions {
        let pool_dir = format!("/etc/php/{php}/fpm/pool.d");
        let entries = match std::fs::read_dir(&pool_dir) {
            Ok(e) => e,
            Err(_) => continue,
        };

        for entry in entries.flatten() {
            let path = entry.path();
            let name = path.file_stem().and_then(|n| n.to_str()).unwrap_or("");
            if name == "www" {
                continue; // skip the shared fallback pool
            }

            let content = std::fs::read_to_string(&path).unwrap_or_default();
            let user = content
                .lines()
                .find(|l| l.starts_with("user = "))
                .map(|l| l.trim_start_matches("user = "))
                .unwrap_or("?")
                .to_string();

            let socket = fpm_socket_path(name, php);
            let socket_exists = Path::new(&socket).exists();
            let socket_display = if socket_exists {
                socket.green().to_string()
            } else {
                socket.dimmed().to_string()
            };

            println!("{:<35} {:<8} {:<20} {}", name, php, user, socket_display);
            found = true;
        }
    }

    if !found {
        println!("{}", "no per-site pools found (only the shared 'www' pool exists)".yellow());
    }

    Ok(())
}

pub fn cmd_remove(domain: &str, php: &str) -> Result<()> {
    let pool_path = fpm_pool_path(domain, php);

    if !pool_path.exists() {
        anyhow::bail!("pool not found at {}", pool_path.display());
    }

    std::fs::remove_file(&pool_path)?;
    println!("{} {}", "removed:".green(), pool_path.display());

    reload_fpm(php)?;
    println!("{} php{php}-fpm", "reloaded:".green());

    Ok(())
}
